In [1]:
l = range(1000000)

In [21]:
%magic

In [2]:
import numpy as np

In [3]:
d = np.arange(1000000)

In [5]:
%time for i in range(1, 10): r = [x*2 for x in l]

Wall time: 997 µs


In [7]:
%time for i in range(1, 10): r = d*2 

Wall time: 40.9 ms


In [9]:
%history

l = range(1000)
import numpy as np
d = np.arange(1000000)
%time for i in range(1, 10): r = [x*2 for x in l]
%time for i in range(1, 10): r = [x*2 for x in l]
%time for i in range(1, 10): r = d*2
%time for i in range(1, 10): r = d*2
%history
%history


In [31]:
%time print("ada")

ada
Wall time: 0 ns


In [63]:
def abc():print("pakistan") #python
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [ ]:
l = [1,3,2]
print(sum(l))
print(np.sum(l))

In [ ]:
l1 = np.arange(1,3000000)
%time l1 + 5

In [ ]:
l1 = np.arange(1,13)

print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

# A Multidimensional Array Object

In [66]:
#l1 = np.arange(1,13).reshape((4,3))
#l1 = np.arange(1,13).reshape((3,4))
#l1 = np.arange(1,13).reshape((2,6))
#l1 = np.arange(1,13).reshape((6,2))
l1 = np.arange(1,13).reshape((12,1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (12, 1)


In [ ]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

# l1[i,j,k]
# l1[slide, row, column]
#l1[1]
#l1[1,2]

In [ ]:
l1 = np.random.randn(3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

In [34]:
x = np.zeros((4,4))

In [36]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.empty((7,7))

array([[1.05427201e-311, 1.05425574e-311, 1.27148792e+136,
        1.01493487e+137, 1.32013134e+180, 2.08340867e-013,
        3.63444093e+228],
       [2.31666249e-013, 1.28625394e+248, 2.62328308e+300,
        3.95614168e+252, 1.65023927e+137, 9.34839993e+025,
        2.15196058e-013],
       [1.82134489e+016, 2.57248971e+064, 1.42417191e+064,
        9.95052550e+044, 1.48858644e+011, 2.12113490e+088,
        1.14837564e+069],
       [2.78747425e+006, 9.00720265e-308, 4.96309582e+030,
        1.58056482e+103, 1.14840129e+069, 2.78747425e+006,
        9.00720265e-308],
       [8.25324896e+015, 3.75969061e+112, 7.06513077e+150,
        8.25984606e+015, 2.26155701e+137, 1.81861582e+044,
        1.97709834e-062],
       [3.67293878e+228, 2.11789793e+088, 2.29214239e+069,
        7.52743996e+073, 6.02135898e+078, 3.63460087e+088,
        1.15048855e+069],
       [4.51917612e+043, 2.12151325e+088, 1.07695879e+026,
        1.23535057e-307, 8.82764047e+025, 1.08556386e-066,
        1.06394625

In [42]:
l = [1, 4, 5, 7]

In [44]:
np.array(l)

array([1, 4, 5, 7])

In [46]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [50]:
x.shape

(4, 4)

In [55]:
x = np.zeros((10, 10))

In [58]:
x.shape

(10, 10)

In [60]:
y = x.reshape((2, 2, 5, 5))

In [69]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [70]:
y.dtype

dtype('float64')

In [71]:
y.ndim

4

In [73]:
a = np.ones((3,2))        # array of 1s
print(a)

b = np.zeros((3,4))       # array of 0s
print(b)

c = np.random.random(3)   # array of random value
print(c)

d = np.full((2,2), 12)    # array filled with constant values
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0.37715362 0.67118314 0.53772951]
[[12 12]
 [12 12]]


# Vectorized Operations

In [81]:
a = np.random.random(10)

In [75]:
b = np.random.random(10)

In [84]:
a

array([0.52729068, 0.98421081, 0.58872533, 0.16273513, 0.48081273,
       0.04854415, 0.19438871, 0.86881119, 0.30334145, 0.65396551])

In [86]:
b

array([-1.16982886,  0.68039564,  0.5156339 , -1.42888638,  1.17026875,
        2.10144962, -0.83982114,  0.67436443,  0.8524497 , -0.85461844])

In [88]:
a + b

array([-0.64253818,  1.66460645,  1.10435923, -1.26615125,  1.65108148,
        2.14999378, -0.64543243,  1.54317562,  1.15579115, -0.20065293])

In [90]:
a - b

array([ 1.69711954,  0.30381517,  0.07309143,  1.59162151, -0.68945602,
       -2.05290547,  1.03420985,  0.19444676, -0.54910825,  1.50858395])

In [92]:
2 * a

array([1.05458136, 1.96842163, 1.17745066, 0.32547026, 0.96162546,
       0.0970883 , 0.38877742, 1.73762238, 0.6066829 , 1.30793101])

In [94]:
1 / a

array([ 1.89648714,  1.01604248,  1.69858498,  6.14495464,  2.07981182,
       20.59980381,  5.14433169,  1.15099807,  3.2966151 ,  1.52913264])

In [96]:
a > 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [98]:
b > 0

array([False,  True,  True, False,  True,  True, False,  True,  True,
       False])

In [103]:
b[b>0]

array([0.68039564, 0.5156339 , 1.17026875, 2.10144962, 0.67436443,
       0.8524497 ])

# Data Types for ndarrays

In [4]:
import numpy as np

In [5]:
a = np.array([1, 3, 4], dtype = 'int')
a.dtype

dtype('int32')

In [6]:
a = np.array([1, 3, 4], dtype = int)
a.dtype

dtype('int32')

In [8]:
a = np.array([1, 3, 4], dtype = np.int64)
a.dtype

dtype('int64')

In [9]:
a = np.array([1, 3, 4], dtype = 'i8')
a.dtype

dtype('int64')

In [10]:
b = np.array([3, 8, 9], dtype = a.dtype)
b.dtype

dtype('int64')

In [11]:
c = a.astype(np.int64)
c.dtype

dtype('int64')

# Boolean Operations

In [14]:
a = np.arange(1, 28).reshape((3, 3, 3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [15]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [16]:
print(a)
a[a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
print(a)
a[(a%3==0) & (a%5==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [19]:
print(a)
a[~a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [20]:
print(a)
a[~(a%3==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [21]:
print(a)
a[a%3!=0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [22]:
a = np.arange(1,7).reshape((2,3,1))
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

# Indexing Slicing

In [ ]:
import numpy as np

In [111]:
x = np.array(([1, 7, 9, 8, 5]))

In [112]:
x[4]

5

In [113]:
x[x>5]

array([7, 9, 8])

In [114]:
x[[2, 1]]          # fancy slicing

array([9, 7])

In [128]:
x = np.random.randn(10, 10)

In [129]:
x

array([[ 1.58100092e-01,  9.83578250e-01,  6.60962124e-01,
        -6.91716045e-01, -2.04379375e+00,  2.11225357e+00,
        -1.70900737e+00,  2.15929870e-01, -1.67349634e-01,
        -9.55252522e-01],
       [-1.99843897e+00, -9.71805625e-01,  1.58658934e+00,
        -1.65247386e+00,  2.66737883e-03,  3.67380292e-01,
         1.60662605e+00,  7.62325961e-01,  1.00801110e+00,
         1.33457488e+00],
       [-2.94488943e-01,  2.98105393e-02, -1.23260249e+00,
         1.17700990e+00,  7.96767287e-01, -3.22396481e-01,
         1.02429964e-01, -3.41745198e-01, -4.99997204e-02,
        -1.22568485e+00],
       [-7.95657970e-01, -2.12971900e+00, -1.45345652e+00,
        -2.51966320e-01,  7.81972002e-01, -3.93762341e-01,
        -8.56004263e-01,  1.88232966e-02, -3.48777149e-01,
        -1.69534374e+00],
       [-1.02711317e+00, -3.80876075e-01, -1.01979548e-01,
        -1.17710795e+00,  9.26356445e-01,  1.14527211e-01,
        -4.30947334e-01, -4.62153523e-01,  1.80885673e-01,
         4.

In [130]:
x[0]

array([ 0.15810009,  0.98357825,  0.66096212, -0.69171604, -2.04379375,
        2.11225357, -1.70900737,  0.21592987, -0.16734963, -0.95525252])

In [131]:
x[0][4]

-2.0437937500949426

In [132]:
x[1:10:2]

array([[-1.99843897e+00, -9.71805625e-01,  1.58658934e+00,
        -1.65247386e+00,  2.66737883e-03,  3.67380292e-01,
         1.60662605e+00,  7.62325961e-01,  1.00801110e+00,
         1.33457488e+00],
       [-7.95657970e-01, -2.12971900e+00, -1.45345652e+00,
        -2.51966320e-01,  7.81972002e-01, -3.93762341e-01,
        -8.56004263e-01,  1.88232966e-02, -3.48777149e-01,
        -1.69534374e+00],
       [ 1.30857374e-01,  4.96299385e-01, -7.80629529e-01,
         8.97763968e-01,  2.28144220e+00,  1.00307896e-01,
         1.91605718e+00,  1.65741013e+00, -1.79958527e+00,
        -1.80791948e+00],
       [ 5.87254930e-01, -8.39651040e-01, -2.48046085e-01,
         7.10982222e-02,  9.97391275e-01, -5.93724794e-01,
        -6.85277775e-01, -2.24778484e-02, -2.94042145e-01,
         6.69198593e-01],
       [ 2.81235605e+00,  2.67662403e-01, -1.51712388e+00,
         9.72729122e-01,  9.69213150e-01, -1.34803462e+00,
        -6.17576159e-01,  4.09677426e-01,  1.89099121e+00,
        -8.

In [133]:
x[::, 0:4]

array([[ 0.15810009,  0.98357825,  0.66096212, -0.69171604],
       [-1.99843897, -0.97180562,  1.58658934, -1.65247386],
       [-0.29448894,  0.02981054, -1.23260249,  1.1770099 ],
       [-0.79565797, -2.129719  , -1.45345652, -0.25196632],
       [-1.02711317, -0.38087607, -0.10197955, -1.17710795],
       [ 0.13085737,  0.49629938, -0.78062953,  0.89776397],
       [ 1.53939524, -0.46065719, -0.66932984,  0.35452085],
       [ 0.58725493, -0.83965104, -0.24804609,  0.07109822],
       [ 0.83508591,  1.39493623, -1.09260661,  2.61144522],
       [ 2.81235605,  0.2676624 , -1.51712388,  0.97272912]])

In [135]:
x = np.ones((5,5))

In [136]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [138]:
x[1:-1, 1:-1] = 0

In [139]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Fancy Slicing

In [23]:
import numpy as np

In [25]:
a = np.arange(10, 3*3*3+10).reshape(3, 3, 3)
print(a)
a[[1, 2, 0]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a[[1,2,0]][:,[0,1,2]]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
names = np.array(["Rutab", "Sania", "Amna", "Husnain", "Rutab", "Ertugrul"])

data = np.random.randn(6,4)

print(names, data, sep="\n\n\n")

['Rutab' 'Sania' 'Amna' 'Husnain' 'Rutab' 'Ertugrul']


[[ 1.90674491  0.55457371 -0.31894771 -0.1687669 ]
 [ 1.04304226  0.63822205 -2.05479821  0.57645438]
 [ 1.94806646  1.33903197 -0.53779343  0.84097999]
 [-0.42046072 -1.20421456  2.28391606 -0.35569575]
 [-1.85716311 -2.46351047 -0.46284606 -0.00682147]
 [ 0.67568809  0.06790735 -1.05125174 -0.23758766]]


In [36]:
names == "Rutab"

array([ True, False, False, False,  True, False])

In [38]:
data[[ True, False, False, False,  True, False]]

array([[ 1.90674491,  0.55457371, -0.31894771, -0.1687669 ],
       [-1.85716311, -2.46351047, -0.46284606, -0.00682147]])

In [40]:
data[names=="Rutab"]

array([[ 1.90674491,  0.55457371, -0.31894771, -0.1687669 ],
       [-1.85716311, -2.46351047, -0.46284606, -0.00682147]])

In [42]:
data[(names=="Rutab") | (names=="Ertugrul")]

array([[ 1.90674491,  0.55457371, -0.31894771, -0.1687669 ],
       [-1.85716311, -2.46351047, -0.46284606, -0.00682147],
       [ 0.67568809,  0.06790735, -1.05125174, -0.23758766]])

In [44]:
data[(names!="Rutab") |  (names!="Ertugrul")]

array([[ 1.90674491,  0.55457371, -0.31894771, -0.1687669 ],
       [ 1.04304226,  0.63822205, -2.05479821,  0.57645438],
       [ 1.94806646,  1.33903197, -0.53779343,  0.84097999],
       [-0.42046072, -1.20421456,  2.28391606, -0.35569575],
       [-1.85716311, -2.46351047, -0.46284606, -0.00682147],
       [ 0.67568809,  0.06790735, -1.05125174, -0.23758766]])

In [51]:
#python
l = [1,3,5,3,5]
l[:3]
l[:3] = 5

TypeError: can only assign an iterable

In [52]:
# NUMPY
l = np.array([1,3,5,3,5])
l[:3]
l[:3] = 5
l

array([5, 5, 5, 3, 5])

In [54]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [55]:
for i in range(len(a)):
    a[i] = i
print(a)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [57]:
for i in range(a.shape[0]):
    a[i] = i
print(a)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [59]:
for i, _ in enumerate(a):
    a[i] = i
print(a)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


# Functions

In [6]:
import numpy as np

In [7]:
x = np.array([10, 9, 8, 6, 11])

In [9]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [11]:
np.power(x, 2)

array([100,  81,  64,  36, 121], dtype=int32)

In [13]:
y = [7, 1, 2, 3, -1]

In [15]:
np.maximum(x, y)

array([10,  9,  8,  6, 11])

# np.where

In [16]:
import numpy as np

In [17]:
salary = np.array([0, -1, 100000, 50000])

In [19]:
np.where(salary<=0, 25000, salary)

array([ 25000,  25000, 100000,  50000])

In [21]:
np.where(salary<=0, "Not Ok", "Ok")

array(['Not Ok', 'Not Ok', 'Ok', 'Ok'], dtype='<U6')

# Statistical Methods

In [24]:
import numpy as np

In [26]:
x = np.array([10, 9, 7, 10, 7])

In [28]:
x.mean()

8.6

In [30]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [32]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [34]:
y = x > 6

In [36]:
y

array([ True,  True,  True,  True,  True])

In [38]:
y.sum()

5

In [40]:
y.any()

True

In [42]:
y.all()

True

In [44]:
y = x > 7

In [46]:
y

array([ True,  True, False,  True, False])

In [48]:
y.sum()

3

In [50]:
y.any()

True

In [52]:
y.all()

False

In [54]:
x

array([10,  9,  7, 10,  7])

In [58]:
x.sort()

In [60]:
x

array([ 7,  7,  9, 10, 10])

In [64]:
np.unique(x)

array([ 7,  9, 10])

# File Input/Output

In [66]:
import numpy as np

In [67]:
x = [1, 4, 5, 7]

In [69]:
y = [8, 7, 9]

In [71]:
np.save('testx', x)

In [74]:
loadx = np.load("testx.npy")

In [76]:
loadx

array([1, 4, 5, 7])

In [89]:
np.savez("testxy", x=x, y=y)

In [91]:
loadxy = np.load("testxy.npz")

In [92]:
loadxy

In [94]:
loadxy['x']

array([1, 4, 5, 7])

In [96]:
loadxy['y']

array([8, 7, 9])

# Linear Algebra Functions

In [98]:
import numpy as np

In [101]:
x = np.random.randn(3, 2)

In [103]:
y = np.random.randn(2, 3)

In [105]:
x.dot(y)

array([[ 0.13441454,  0.31650613,  0.30829889],
       [ 0.33560676,  0.36673807, -2.82369758],
       [-0.62315958, -0.96530812,  2.83047678]])

In [107]:
x.transpose()

array([[ 0.9782638 , -1.78759779,  0.47917778],
       [ 0.39681814,  0.66690163, -1.45575899]])

In [109]:
x.trace()

1.6451654303902976

# Transposing Arrays & Swaping Axes

In [5]:
import numpy as np

In [8]:
a = np.arange(4*3).reshape(4, 3)

print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [12]:
a.T.T.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [15]:
a.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [23]:
a = np.array([[1, 2], [3, 4]])

b = a + 2

print(a, b, sep="\n\n", end="\n\n")

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



In [28]:
a * b          # Elements wise array multiplication

array([[ 3,  8],
       [15, 24]])

In [30]:
a @ b          # Full array Multiplication

array([[13, 16],
       [29, 36]])

In [32]:
a.dot(b)

array([[13, 16],
       [29, 36]])

In [34]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [37]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [41]:
a.transpose(2, 1, 0)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [43]:
a.swapaxes(2, 1)

array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

# Pseudo Random Number

In [45]:
import numpy as np

In [47]:
np.random.seed(7)

In [48]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [50]:
np.random.uniform(size=(3, 4))

array([[0.06593635, 0.2881456 , 0.90959353, 0.21338535],
       [0.45212396, 0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992, 0.90912837]])

# reshape()

In [1]:
import numpy as np

In [3]:
x = np.random.randn(4, 5)

In [5]:
x

array([[-0.42235285, -0.03418138,  0.26459774, -0.09871468,  1.13647309],
       [-0.75063968,  1.89850909, -0.37862163,  1.05399368, -0.67461532],
       [ 0.0335182 ,  0.76243094, -1.49163031,  0.46531896, -1.04270835],
       [ 1.36266553, -0.0768131 , -1.28665956, -0.14476437,  1.32352618]])

In [8]:
x.reshape(2, 2, 5)

array([[[-0.42235285, -0.03418138,  0.26459774, -0.09871468,
          1.13647309],
        [-0.75063968,  1.89850909, -0.37862163,  1.05399368,
         -0.67461532]],

       [[ 0.0335182 ,  0.76243094, -1.49163031,  0.46531896,
         -1.04270835],
        [ 1.36266553, -0.0768131 , -1.28665956, -0.14476437,
          1.32352618]]])

In [17]:
x.reshape((2, 2, 5), order='F')

array([[[-0.42235285, -0.03418138,  0.26459774, -0.09871468,
          1.13647309],
        [ 0.0335182 ,  0.76243094, -1.49163031,  0.46531896,
         -1.04270835]],

       [[-0.75063968,  1.89850909, -0.37862163,  1.05399368,
         -0.67461532],
        [ 1.36266553, -0.0768131 , -1.28665956, -0.14476437,
          1.32352618]]])

In [18]:
x.reshape((2, 2, 5), order='C')

array([[[-0.42235285, -0.03418138,  0.26459774, -0.09871468,
          1.13647309],
        [-0.75063968,  1.89850909, -0.37862163,  1.05399368,
         -0.67461532]],

       [[ 0.0335182 ,  0.76243094, -1.49163031,  0.46531896,
         -1.04270835],
        [ 1.36266553, -0.0768131 , -1.28665956, -0.14476437,
          1.32352618]]])

In [20]:
x.reshape(2, 2, -1)

array([[[-0.42235285, -0.03418138,  0.26459774, -0.09871468,
          1.13647309],
        [-0.75063968,  1.89850909, -0.37862163,  1.05399368,
         -0.67461532]],

       [[ 0.0335182 ,  0.76243094, -1.49163031,  0.46531896,
         -1.04270835],
        [ 1.36266553, -0.0768131 , -1.28665956, -0.14476437,
          1.32352618]]])

In [22]:
x

array([[-0.42235285, -0.03418138,  0.26459774, -0.09871468,  1.13647309],
       [-0.75063968,  1.89850909, -0.37862163,  1.05399368, -0.67461532],
       [ 0.0335182 ,  0.76243094, -1.49163031,  0.46531896, -1.04270835],
       [ 1.36266553, -0.0768131 , -1.28665956, -0.14476437,  1.32352618]])

In [24]:
x.ravel()

array([-0.42235285, -0.03418138,  0.26459774, -0.09871468,  1.13647309,
       -0.75063968,  1.89850909, -0.37862163,  1.05399368, -0.67461532,
        0.0335182 ,  0.76243094, -1.49163031,  0.46531896, -1.04270835,
        1.36266553, -0.0768131 , -1.28665956, -0.14476437,  1.32352618])

In [26]:
x.flatten()

array([-0.42235285, -0.03418138,  0.26459774, -0.09871468,  1.13647309,
       -0.75063968,  1.89850909, -0.37862163,  1.05399368, -0.67461532,
        0.0335182 ,  0.76243094, -1.49163031,  0.46531896, -1.04270835,
        1.36266553, -0.0768131 , -1.28665956, -0.14476437,  1.32352618])

# concatenate()

In [28]:
import numpy as np

In [30]:
x = [[1, 3, 5], [7, 9, 0]]

In [32]:
arr1 = np.array(x)

In [34]:
y = [[11, 13, 15], [17, 19, 10]]

In [36]:
arr2 = np.array(y)

In [38]:
np.concatenate((arr1, arr2), axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [40]:
np.concatenate((arr1, arr2), axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [43]:
np.vstack((arr1, arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [45]:
np.hstack((arr1, arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

# Chaining

In [47]:
def A(x): return x + 5
def B(x): return x + 6
def C(x): return x + 7    

In [49]:
C(B(A(1)))

19

In [51]:
A(B(C(1)))

19

In [ ]:
np.A().B().C()

In [54]:
#arange().reshape()
#np.ones
#np.ones_like
#np.zeros
#np.zeros_like
#np.full
#np.full_like
#np.empty
#np.empty_like

In [58]:
a = np.arange(1, 28).reshape(3, 3, 3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
a.ndim

3

In [66]:
a.shape = (3, 9)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [68]:
a.ndim

2

In [73]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [75]:
a.shape

(9, 3)

In [79]:
np.zeros((3, 9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
np.zeros((a.shape[0], a.shape[1]))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.zeros(a.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [86]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [89]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
b = np.ones_like(a)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [94]:
b = np.ones_like(a) * 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [96]:
b = np.full((3, 3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [98]:
b = np.full_like(a, 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [100]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [102]:
np.full_like(a, dtype=a.dtype, fill_value = 2.5)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [104]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [108]:
np.empty((3, 9))

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [110]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [112]:
np.full_like(a, 1) * np.nan

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [114]:
np.full(a.shape, np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [116]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [119]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# split()

In [121]:
import numpy as np

In [123]:
x = [1, 4, 5, 6, 7, 9, 1, 4]

In [125]:
d = np.array(x)

In [127]:
np.split(d, [2, 5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [128]:
x = [[1, 4, 5, 6, 7, 9, 1, 4], [11, 14, 15, 16, 17, 19, 11, 14]]

In [130]:
d = np.array(x)

In [132]:
np.split(d, [4, 6], axis=1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]), array([[ 7,  9],
        [17, 19]]), array([[ 1,  4],
        [11, 14]])]

In [134]:
np.split(d, [1], axis=0)

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]

# repeat / Tile

In [136]:
import numpy as np

In [138]:
d = np.array([1, 5, 7, 8])

In [140]:
np.repeat(d, 3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [142]:
np.tile(d, 2)

array([1, 5, 7, 8, 1, 5, 7, 8])